### ISSUE TITLE
Import and export aren't recognized

### ISSUE THREAD

**Issue by gballet** [nblackburn/vue-brunch#19]
FYI, I am using `vue-brunch` in a Phoenix context. I have copied my .vue files to `web/static/js` and the plugin finds and compile them.

I initially had an issue with the babel configuration, but I copied it from the source repo where I found the `.vue` file.

```
{
  "presets": [
    ["latest", {
      "es2015": { "modules": false }
    }]
  ]
}
```

It then complains that import and export aren't valid tokens: `Uncaught SyntaxError: Unexpected token export` which points at the `.vue` file's main statement:

```
<script>
export default {
  data: () => { ... },
  ...
};
</script>
```

I tried to set `modules` to `commonjs` but then it complains about not being able to find some vueify module:

```
Uncaught Error: Cannot find module 'vueify/lib/insert-css' from 'web/static/js/SvgVueR.vue'
```

`amd` and `systemjs` have similar issues.

Any idea what might go wrong?

**Comment by nblackburn** [comment]
Can you setup a repo demonstrating this issue and i will look into it.

**Comment by gballet** [comment]
You can find a simplified Phoenix project that reproduces the issue there:

https://github.com/gballet/phoenix_vue_brunch_issue

**Comment by gballet** [comment]
This gentleman has found a workaround when setting `commonjs` in the `.babelrc` file.

https://gist.github.com/jlauemoeller/d53ddd028387cd139c31bf2282dd12f4

 Basically, the idea is to not use `vuefiy/lib/insert-css` which is causing the problem.

I'm still wondering why I have to go with `commonjs` in Phoenix when `export`-style statement seem to work in a standalone brunch project?

**Comment by brandonparsons** [comment]
@gballet Did you sort this out? I seem to be having the same issue... I can use `commonjs` format, but I'd like to use `es2015`.

**Comment by brandonparsons** [comment]
Can confirm I'm getting the same issue. Can't seem to get this working with Vue 2.0, and es2015 modules.

**Comment by gballet** [comment]
@brandonparsons nope, haven't been able to use es2015 modules. Just out of curiosity, are you using a Phoenix application or a standalone brunch app?

**Comment by brandonparsons** [comment]
@gballet Through Phoenix, so figure we're having the same issues :)

I got it kind of working - it required that I bundle the full version of Vue (i.e. not just the runtime). Adds a bit to the bundle size, but at least it works.

**Comment by imetallica** [comment]
@brandonparsons @gballet are you using Phoenix 1.2? The default version of brunch in 1.2 is old, I suggest upgrading to the latest version. That solved many of the issues I've had with vue-brunch.

**Comment by gballet** [comment]
@imetallica I just ran `mix deps.update` to upgrade to phoenix 1.2.3 (the latest according to `mix hex.outdated` at this time) and the problem is still here. I ran `npm update` just to be sure and it's not changing anything.

**Comment by gballet** [comment]
@brandonparsons from what I understand, the `export` statement should be transpiled. With your fix (or workaround?), how does it get transpiled?

**Comment by imetallica** [comment]
@gballet I mean, update your dependencies on NPM. Phoenix doesn't have anything to do with NPM.

**Comment by imetallica** [comment]
@gballet also, you need something like this

```
plugins: {
    ...
    vue: {
      extractCSS: true,
      out: '../priv/static/css/components.css'
    }
    ...
}
```

**Comment by gballet** [comment]
@nblackburn @brandonparsons I have managed to solve the problem. It seems that the issue is with using `babel-preset-latest` instead of `babel-preset-es2015`. Both have the same version, `6.24.0`.

Also, the `.babelrc` needs to be updated to reflect that change, from:

```javascript

{
  "presets": [
    ["latest", {
      "es2015": { "modules": false }
    }]
  ]
}
```

to:

```javascript
{
  "presets": ["es2015"]
}
```

Could you please confirm that this solves the problem on your end, so that I can close the issue?

Also, @imetallica thanks for your help.

**Comment by nblackburn** [comment]
@gballet Glad you got it sorted in the end, i am unable to confirm this fixes the issue so will have to take your word for it on this occasion.

I will wait for @brandonparsons first and if they are happy then this can be closed.

**Comment by brandonparsons** [comment]
@gballet How did you *not* use `babel-preset-latest`? It is a dependency of `babel-brunch` @ 6.1.1.

**Comment by brandonparsons** [comment]
@gballet I've tried blowing everything away, and even installing `babel-brunch` from the Github master (they have replaced `babel-preset-latest` with `babel-preset-env`).  

I still get the following error unless I tell brunch to use the full version of vue (not runtime only):

`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
(found in <Root>)`. It doesn't appear to be properly compiling the single-file vue component (I have a test component set to render on the page).

Here is my package.json:

```
{
  // .....
  "dependencies": {
    // .......
    "phoenix": "file:../../../deps/phoenix",
    "phoenix_html": "file:../../../deps/phoenix_html",
    "vue": "^2.2.6"
  },
  "devDependencies": {
    // .....
    "babel-brunch": "github:babel/babel-brunch#c42c598076dcdd44f5dbe3c310f78e06e992c6e1",
    "babel-core": "^6.24.0",
    "babel-preset-es2015": "^6.24.0",
    "brunch": "^2.10.9",
    "uglify-js-brunch": "^2.10.0",
    "vue-brunch": "^2.0.1"
  }
}
```

I have to add the following to `brunch-config.js` to get it to work:

```
    aliases: {
      "vue": "vue/dist/vue.common.js"
    }
```

**Comment by brandonparsons** [comment]
I sorted out the problem.

Everything was working fine. The issue was that when I was bootstrapping the Vue instance on my test page, I was using the `el` option in the Vue constructor.  This apparently uses template compilation. If you want to use the runtime-only version of Vue, you have to bootstrap your root component using a `render` function.

This issue can be closed.

**Comment by imetallica** [comment]
@nblackburn actually can you update the README to the changes that need to be done if you want to use the `vue.common.js`, so you can create single file components and export the css from these components.

The changes are the following

```
plugins: {
    vue: {
      extractCSS: true,
      out: '../priv/static/css/components.css'
    }
},
npm: {
  aliases: {
    "vue": "vue/dist/vue.common.js"
  }
}
```

**Comment by nblackburn** [comment]
@imetallica I will update the README with instructions on extracting CSS but using the correct build of Vue dependent on the use case is out of scope for this project.
